apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: ride-sharing/driver-service
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "125m"
          env:
            # Accessing an env variable from the app-config config map
            - name: GATEWAY_HTTP_ADDR
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_HTTP_ADDR
                  name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: driver-service
